name: secure_env_core
description: Core functionality for secure environment variable management
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3
  encrypt: ^5.0.3
  crypto: ^3.0.6
  meta: ^1.16.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
