name: secure_env
description: A CLI tool for managing environment variables securely
version: 1.0.0
homepage: https://github.com/ketanchoyal/secure_env

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  encrypt: ^5.0.3
  crypto: ^3.0.3
  path: ^1.8.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.11
  yaml: ^3.1.2
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.9
  mocktail: ^1.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

executables:
  secure-env: secure_env
