name: secure_env_cli
description: A CLI tool for managing environment variables securely
version: 1.0.0
repository: https://github.com/ketanchoyal/secure_env

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.7.0
  mason_logger: ^0.3.3
  yaml: ^3.1.3
  secure_env_core:
    path: ../secure_env_core

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  mocktail: ^1.0.4
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4

executables:
  secure-env: secure_env
